Fix weath Works the same as before, but prints to terminal rather than displaying a notification. Main issue was a second less here would run if the first succeeded: less -S "$report" || data="$(curl -sfm 5 "${WTTRURL:-wttr.in}/$1")" && echo "$data" | less -S

diff --git a/.local/bin/weath b/.local/bin/weath
--- a/.local/bin/weath
+++ b/.local/bin/weath
@@ -1,25 +1,21 @@
 #!/bin/sh
-#
-# Get the weather on the terminal. You can pass an alternative location as a parameter,
-# and/or use the 'cp' option to copy the forecast as plaintext to the clipboard.
+
+# Get the weather on the terminal. An alternative location can be passed as an
+# argument, and/or 'cp' to copy the forecast as plaintext to the clipboard.
+
+[ "$1" = cp ] && copy=true && shift
+
+[ -n "$2" ] && { printf "Invalid option '%s'! The only valid option is 'cp'.\n" "$1" >&2; exit 1 ;}
 
 report="${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"
 
-if [ "$1" = 'cp' ]; then
-        # shellcheck disable=SC2015
-        [ -z "$2" ] && sed 's/\x1b\[[^m]*m//g' "$report" | xclip -selection clipboard &&
-                notify-send "Weather forecast for '${LOCATION:-$(head -n 1 "$report" | cut -d' ' -f3-)}' copied to clipboard." ||
-                        { data="$(curl -sfm 5 "${WTTRURL:-wttr.in}/$2?T")" &&
-                        notify-send "Weather forecast for '$2' copied to clipboard." &&
-                        echo "$data" | xclip -selection clipboard ||
-                        notify-send 'Failed to get weather forecast!' 'Check your internet connection and the supplied location.'; }
-else
-        [ -n "$2" ] &&
-                notify-send "Invalid option '$1'! The only valid option is 'cp'." &&
-                exit 1
+data="$([ -z "$1" ] && cat "$report" 2>/dev/null || curl -sfm 5 "${WTTRURL:-wttr.in}/$1${copy:+?T}")" ||
+	{ printf "Failed to get weather forecast!\nCheck your internet connection and the supplied location.\n" >&2; exit 1 ;}
 
-        # shellcheck disable=SC2015
-        [ -z "$1" ] && less -S "$report" ||
-                data="$(curl -sfm 5 "${WTTRURL:-wttr.in}/$1")" && echo "$data" | less -S ||
-                        notify-send 'Failed to get weather forecast!' 'Check your internet connection and the supplied location.'
-fi
+[ -n "$copy" ] && {
+	[ -z "$1" ] && read -r location <"$report" && location="${location#*: }"
+	echo "$data" | sed 's/\x1b\[[^m]*m//g' | xclip -selection clipboard
+	printf "Weather forecast for '%s' copied to clipboard.\n" "${1:-$location}"
+	exit ;}
+
+echo "$data" | less -S
